# Generated by Django 6.0.2 on 2026-02-04 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("memo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="folder",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="user",
        ),
        migrations.RemoveField(
            model_name="note",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="note",
            name="content",
        ),
        migrations.RemoveField(
            model_name="note",
            name="is_archived",
        ),
        migrations.DeleteModel(
            name="Folder",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
